import type { PublicEvidenceTargetStatus } from './public-evidence-navigation-core.js';

export type PublicEvidenceTargetRecord = readonly [
  evidenceId: string,
  path: string,
  label: string,
  status: PublicEvidenceTargetStatus,
];
export const publicEvidenceTargetRecords: readonly PublicEvidenceTargetRecord[] = [
  ['portfolio:source:project:job-search-os', '/work/job-search-os', 'Job Search OS case study', 'available'],
  ['portfolio:claim:job-search-os:integrated-workflow', '/work/job-search-os', 'Job Search OS integrated workflow', 'available'],
  ['portfolio:claim:job-search-os:evidence-fallbacks', '/work/job-search-os', 'Job Search OS evidence and fallbacks', 'available'],
  ['portfolio:claim:job-search-os:approval-boundary', '/work/job-search-os', 'Job Search OS approval boundary', 'available'],
  ['portfolio:limitation:project:job-search-os', '/work/job-search-os', 'Job Search OS current boundaries', 'available'],
  ['portfolio:source:project:flight-tracker-ai', '/work/flight-tracker-ai', 'Flight Tracker AI case study', 'available'],
  ['portfolio:claim:flight-tracker-ai:live-replay', '/work/flight-tracker-ai', 'Flight Tracker AI live and replay modes', 'available'],
  ['portfolio:claim:flight-tracker-ai:geospatial-context', '/work/flight-tracker-ai', 'Flight Tracker AI geospatial context', 'available'],
  ['portfolio:claim:flight-tracker-ai:typed-system', '/work/flight-tracker-ai', 'Flight Tracker AI typed system', 'available'],
  ['portfolio:limitation:project:flight-tracker-ai', '/work/flight-tracker-ai', 'Flight Tracker AI current boundaries', 'available'],
  ['portfolio:source:project:wave-factory-essentials', '/work/wave-factory-essentials', 'Wave Factory Essentials case study', 'available'],
  ['portfolio:claim:wave-factory-essentials:plugin-formats', '/work/wave-factory-essentials', 'Wave Factory plug-in formats', 'available'],
  ['portfolio:claim:wave-factory-essentials:local-dsp', '/work/wave-factory-essentials', 'Wave Factory local DSP', 'available'],
  ['portfolio:claim:wave-factory-essentials:release-gates', '/work/wave-factory-essentials', 'Wave Factory release gates', 'available'],
  ['portfolio:limitation:project:wave-factory-essentials', '/work/wave-factory-essentials', 'Wave Factory current boundaries', 'available'],
  ['portfolio:source:experience:yubico', '/experience', 'Yubico experience', 'available'],
  ['portfolio:source:experience:revenue-io', '/experience', 'Revenue.io experience', 'available'],
  ['portfolio:source:experience:bosch', '/experience', 'Bosch experience', 'available'],
  ['portfolio:source:experience:bridg', '/experience', 'Bridg experience', 'available'],
  ['portfolio:source:experience:grindr', '/experience', 'Grindr experience', 'available'],
  ['portfolio:capability:product-interface-systems:yubico', '/capabilities', 'Product interface systems: Yubico', 'available'],
  ['portfolio:capability:product-interface-systems:revenue-io', '/capabilities', 'Product interface systems: Revenue.io', 'available'],
  ['portfolio:capability:product-interface-systems:flight-tracker-ai', '/capabilities', 'Product interface systems: Flight Tracker AI', 'available'],
  ['portfolio:capability:bounded-ai-workflows:job-search-os', '/capabilities', 'Bounded AI workflows: Job Search OS', 'available'],
  ['portfolio:capability:bounded-ai-workflows:supraconscious-avatar-ai', '/capabilities', 'Bounded AI workflows: Supraconscious Avatar AI', 'available'],
  ['portfolio:capability:bounded-ai-workflows:fruition-venture-studio', '/capabilities', 'Bounded AI workflows: Fruition Venture Studio', 'available'],
  ['portfolio:capability:security-and-platform-boundaries:yubico', '/capabilities', 'Security boundaries: Yubico', 'available'],
  ['portfolio:capability:security-and-platform-boundaries:webauthn-core', '/capabilities', 'Security boundaries: WebAuthn Core', 'available'],
  ['portfolio:capability:security-and-platform-boundaries:job-search-os', '/capabilities', 'Security boundaries: Job Search OS', 'available'],
  ['portfolio:capability:creative-technology:wave-factory-essentials', '/capabilities', 'Creative technology: Wave Factory Essentials', 'available'],
  ['portfolio:capability:creative-technology:progression-lab-ai', '/capabilities', 'Creative technology: ProgressionLab', 'available'],
  ['portfolio:capability:creative-technology:emf-disturbance-sim', '/capabilities', 'Creative technology: EMF Disturbance Sim', 'available'],
  ['portfolio:capability:technical-leadership:bosch', '/capabilities', 'Technical leadership: Bosch', 'available'],
  ['portfolio:capability:technical-leadership:grindr', '/capabilities', 'Technical leadership: Grindr', 'available'],
  ['portfolio:source:recommendation:sree-sankara-2026-06-02', '/recommendations', 'Sree Sankara recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:corbett-trubey-2017-09-15', '/recommendations', 'Corbett Trubey recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:jason-conover-2017-07-17', '/recommendations', 'Jason Conover recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:shervin-kayvon-2017-07-12', '/recommendations', 'Shervin Kayvon recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:justin-treen-2016-03-13', '/recommendations', 'Justin Treen recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:todd-rimes-2013-08-13', '/recommendations', 'Todd Rimes recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:jim-talbot-2012-07-31', '/recommendations', 'Jim Talbot recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:evan-astrowsky-2012-02-15', '/recommendations', 'Evan Astrowsky recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:justin-treen-2011-06-30', '/recommendations', 'Justin Treen recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:david-allen-2011-06-23', '/recommendations', 'David Allen recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:robert-peake-2011-06-18', '/recommendations', 'Robert Peake recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:jacob-tell-2011-06-17', '/recommendations', 'Jacob Tell recommendation candidate', 'review_required'],
  ['portfolio:source:recommendation:laura-baran-2008-02-02', '/recommendations', 'Laura Baran recommendation candidate', 'review_required'],
];
