import type { PublicEvidenceTargetStatus } from './public-evidence-navigation-core.js';

export type PublicEvidenceTargetRecord = readonly [
  evidenceId: string,
  path: string,
  label: string,
  status: PublicEvidenceTargetStatus,
];
export const publicEvidenceTargetRecords: readonly PublicEvidenceTargetRecord[] = [
  ['portfolio:source:project:job-search-os', '/work/job-search-os', 'Job Search OS case study', 'available'],
  ['portfolio:claim:job-search-os:integrated-workflow', '/work/job-search-os', 'Job Search OS integrated workflow', 'available'],
  ['portfolio:claim:job-search-os:evidence-fallbacks', '/work/job-search-os', 'Job Search OS evidence and fallbacks', 'available'],
  ['portfolio:claim:job-search-os:approval-boundary', '/work/job-search-os', 'Job Search OS approval boundary', 'available'],
  ['portfolio:limitation:project:job-search-os', '/work/job-search-os', 'Job Search OS case study', 'available'],
  ['portfolio:source:project:flight-tracker-ai', '/work/flight-tracker-ai', 'Flight Tracker AI case study', 'available'],
  ['portfolio:claim:flight-tracker-ai:live-replay', '/work/flight-tracker-ai', 'Flight Tracker AI live and replay modes', 'available'],
  ['portfolio:claim:flight-tracker-ai:geospatial-context', '/work/flight-tracker-ai', 'Flight Tracker AI geospatial context', 'available'],
  ['portfolio:claim:flight-tracker-ai:typed-system', '/work/flight-tracker-ai', 'Flight Tracker AI typed system', 'available'],
  ['portfolio:limitation:project:flight-tracker-ai', '/work/flight-tracker-ai', 'Flight Tracker AI case study', 'available'],
  ['portfolio:source:project:wave-factory-essentials', '/work/wave-factory-essentials', 'Wave Factory Essentials case study', 'available'],
  ['portfolio:claim:wave-factory-essentials:plugin-formats', '/work/wave-factory-essentials', 'Wave Factory plug-in formats', 'available'],
  ['portfolio:claim:wave-factory-essentials:local-dsp', '/work/wave-factory-essentials', 'Wave Factory local DSP', 'available'],
  ['portfolio:claim:wave-factory-essentials:release-gates', '/work/wave-factory-essentials', 'Wave Factory release gates', 'available'],
  ['portfolio:limitation:project:wave-factory-essentials', '/work/wave-factory-essentials', 'Wave Factory Essentials case study', 'available'],
  ['portfolio:source:project:supraconscious-avatar-ai', '/work/supraconscious-avatar-ai', 'Supraconscious Avatar AI case study', 'available'],
  ['portfolio:claim:supraconscious-avatar-ai:multi-app-system', '/work/supraconscious-avatar-ai', 'Supraconscious Avatar AI multi-app system', 'available'],
  ['portfolio:claim:supraconscious-avatar-ai:policy-first-retrieval', '/work/supraconscious-avatar-ai', 'Supraconscious Avatar AI governed retrieval', 'available'],
  ['portfolio:claim:supraconscious-avatar-ai:separate-control-plane', '/work/supraconscious-avatar-ai', 'Supraconscious Avatar AI control plane', 'available'],
  ['portfolio:limitation:project:supraconscious-avatar-ai', '/work/supraconscious-avatar-ai', 'Supraconscious Avatar AI case study', 'available'],
  ['portfolio:source:project:argent-matchmaking', '/work/argent-matchmaking', 'Argent Matchmaking case study', 'available'],
  ['portfolio:claim:argent-matchmaking:multi-app-foundation', '/work/argent-matchmaking', 'Argent multi-app foundation', 'available'],
  ['portfolio:claim:argent-matchmaking:contract-boundaries', '/work/argent-matchmaking', 'Argent contract and policy boundaries', 'available'],
  ['portfolio:claim:argent-matchmaking:docker-ci-foundation', '/work/argent-matchmaking', 'Argent Docker and CI foundation', 'available'],
  ['portfolio:limitation:project:argent-matchmaking', '/work/argent-matchmaking', 'Argent Matchmaking case study', 'available'],
  ['portfolio:source:project:jolene-ai', '/work/jolene-ai', 'Jolene AI case study', 'available'],
  ['portfolio:claim:jolene-ai:architecture', '/work/jolene-ai', 'Jolene architecture', 'available'],
  ['portfolio:claim:jolene-ai:model', '/work/jolene-ai', 'Jolene model boundary', 'available'],
  ['portfolio:claim:jolene-ai:rag', '/work/jolene-ai', 'Jolene public RAG', 'available'],
  ['portfolio:claim:jolene-ai:corpus', '/work/jolene-ai', 'Jolene evidence corpus', 'available'],
  ['portfolio:claim:jolene-ai:security', '/work/jolene-ai', 'Jolene security boundaries', 'available'],
  ['portfolio:claim:jolene-ai:personality', '/work/jolene-ai', 'Jolene personality system', 'available'],
  ['portfolio:claim:jolene-ai:docker', '/work/jolene-ai', 'Jolene Docker runtime', 'available'],
  ['portfolio:claim:jolene-ai:slack', '/work/jolene-ai', 'Jolene Slack adapter', 'available'],
  ['portfolio:claim:jolene-ai:portfolio-bff', '/work/jolene-ai', 'Jolene portfolio integration', 'available'],
  ['portfolio:claim:jolene-ai:deployment', '/work/jolene-ai', 'Jolene release system', 'available'],
  ['portfolio:claim:jolene-ai:carl-role', '/work/jolene-ai', 'Carl’s role building Jolene', 'available'],
  ['portfolio:claim:jolene-ai:limitations', '/work/jolene-ai', 'What public Jolene can and cannot do', 'available'],
  ['portfolio:limitation:project:jolene-ai', '/work/jolene-ai', 'Jolene AI case study', 'available'],
  ['portfolio:source:experience:yubico', '/experience', 'Yubico experience', 'available'],
  ['portfolio:source:experience:revenue-io', '/experience', 'Revenue.io experience', 'available'],
  ['portfolio:source:experience:bosch', '/experience', 'Bosch experience', 'available'],
  ['portfolio:source:experience:bridg', '/experience', 'Bridg experience', 'available'],
  ['portfolio:source:experience:grindr', '/experience', 'Grindr experience', 'available'],
  ['portfolio:capability:product-interface-systems:yubico', '/capabilities', 'Product interface systems: Yubico', 'available'],
  ['portfolio:capability:product-interface-systems:revenue-io', '/capabilities', 'Product interface systems: Revenue.io', 'available'],
  ['portfolio:capability:product-interface-systems:flight-tracker-ai', '/capabilities', 'Product interface systems: Flight Tracker AI', 'available'],
  ['portfolio:capability:bounded-ai-workflows:job-search-os', '/capabilities', 'Bounded AI workflows: Job Search OS', 'available'],
  ['portfolio:capability:bounded-ai-workflows:supraconscious-avatar-ai', '/capabilities', 'Bounded AI workflows: Supraconscious Avatar AI', 'available'],
  ['portfolio:capability:bounded-ai-workflows:fruition-venture-studio', '/capabilities', 'Bounded AI workflows: Fruition Venture Studio', 'available'],
  ['portfolio:capability:security-and-platform-boundaries:yubico', '/capabilities', 'Security boundaries: Yubico', 'available'],
  ['portfolio:capability:security-and-platform-boundaries:webauthn-core', '/capabilities', 'Security boundaries: WebAuthn Core', 'available'],
  ['portfolio:capability:security-and-platform-boundaries:job-search-os', '/capabilities', 'Security boundaries: Job Search OS', 'available'],
  ['portfolio:capability:creative-technology:wave-factory-essentials', '/capabilities', 'Creative technology: Wave Factory Essentials', 'available'],
  ['portfolio:capability:creative-technology:progression-lab-ai', '/capabilities', 'Creative technology: ProgressionLab', 'available'],
  ['portfolio:capability:creative-technology:emf-disturbance-sim', '/capabilities', 'Creative technology: EMF Disturbance Sim', 'available'],
  ['portfolio:capability:technical-leadership:bosch', '/capabilities', 'Technical leadership: Bosch', 'available'],
  ['portfolio:capability:technical-leadership:grindr', '/capabilities', 'Technical leadership: Grindr', 'available'],
  ['portfolio:source:recommendation:sree-sankara-2026-06-02', '/recommendations', 'Recommendation from Sree Sankara', 'available'],
  ['portfolio:source:recommendation:corbett-trubey-2017-09-15', '/recommendations', 'Recommendation from Corbett Trubey', 'available'],
  ['portfolio:source:recommendation:jason-conover-2017-07-17', '/recommendations', 'Recommendation from Jason Conover', 'available'],
  ['portfolio:source:recommendation:shervin-kayvon-2017-07-12', '/recommendations', 'Recommendation from Shervin Kayvon', 'available'],
  ['portfolio:source:recommendation:justin-treen-2016-03-13', '/recommendations', 'Recommendation from Justin Treen', 'available'],
  ['portfolio:source:recommendation:todd-rimes-2013-08-13', '/recommendations', 'Recommendation from Todd Rimes', 'available'],
  ['portfolio:source:recommendation:jim-talbot-2012-07-31', '/recommendations', 'Recommendation from Jim Talbot', 'available'],
  ['portfolio:source:recommendation:evan-astrowsky-2012-02-15', '/recommendations', 'Recommendation from Evan Astrowsky', 'available'],
  ['portfolio:source:recommendation:justin-treen-2011-06-30', '/recommendations', 'Recommendation from Justin Treen', 'available'],
  ['portfolio:source:recommendation:david-allen-2011-06-23', '/recommendations', 'Recommendation from David Allen', 'available'],
  ['portfolio:source:recommendation:robert-peake-2011-06-18', '/recommendations', 'Recommendation from Robert Peake', 'available'],
  ['portfolio:source:recommendation:jacob-tell-2011-06-17', '/recommendations', 'Recommendation from Jacob Tell', 'available'],
  ['portfolio:source:recommendation:laura-baran-2008-02-02', '/recommendations', 'Recommendation from Laura Baran', 'available'],
];
