export type GitHubProject = {
  name: string;
  description: string;
  language: string | null;
  url: string;
  homepage: string | null;
  updatedAt: string;
  topics: string[];
  stars: number;
  kind: 'application' | 'library' | 'legacy' | 'profile';
};

export const githubSnapshotDate = '2026-08-25';
export const githubSnapshotLabel = 'August 25, 2026';

export const githubProjects: GitHubProject[] = [
  {
    name: 'earth-atlas-ai',
    description: 'EchoAtlas is a planned civilian SAR intelligence workbench for deterministic infrastructure-change candidates, evidence, and human-reviewed assessments.',
    language: 'Python',
    url: 'https://github.com/carlwelchdesign/earth-atlas-ai',
    homepage: null,
    updatedAt: '2026-08-26T03:44:09Z',
    topics: ['FastAPI', 'React', 'TypeScript', 'SAR', 'geospatial'],
    stars: 0,
    kind: 'application',
  },
  {
    name: 'jolene-ai',
    description: 'A policy-gated personal chief-of-staff agent with Slack, governed memory, approvals, workflows, and read-only project awareness.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/jolene-ai',
    homepage: null,
    updatedAt: '2026-08-26T01:18:42Z',
    topics: ['AI agents', 'Slack', 'approvals', 'memory'],
    stars: 0,
    kind: 'application',
  },
  {
    name: 'supraconscious-avatar-ai',
    description: 'A full-stack AI reflection platform that turns journaling into structured patterns, contradictions, and behavioral insights over time.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/supraconscious-avatar-ai',
    homepage: 'https://supraconscious-avatar-ai.vercel.app',
    updatedAt: '2026-08-25T19:58:28Z',
    topics: ['Next.js', 'Flutter', 'GraphRAG', 'MCP', 'PostgreSQL'],
    stars: 0,
    kind: 'application',
  },
  {
    name: 'matchmaker-ai',
    description: 'Argent is a human-led matchmaking concept spanning public and staff web apps, mobile clients, an API, background work, and framework-light domain policy.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/matchmaker-ai',
    homepage: null,
    updatedAt: '2026-08-25T04:57:13Z',
    topics: ['Next.js', 'Flutter', 'Fastify', 'PostgreSQL', 'Redis'],
    stars: 0,
    kind: 'application',
  },
  {
    name: 'carlwelchdesign',
    description: 'The source repository for Carl Welch’s public GitHub profile README.',
    language: null,
    url: 'https://github.com/carlwelchdesign/carlwelchdesign',
    homepage: null,
    updatedAt: '2026-08-24T23:29:36Z',
    topics: ['GitHub profile'],
    stars: 0,
    kind: 'profile',
  },
  {
    name: 'flight-tracker-ai',
    description: 'An aviation-intelligence demo for exploring regional aircraft, weather, trajectories, and explainable attention signals on one navigable map.',
    language: 'Rust',
    url: 'https://github.com/carlwelchdesign/flight-tracker-ai',
    homepage: 'https://flight-tracker-ai-one.vercel.app',
    updatedAt: '2026-08-11T19:57:33Z',
    topics: ['Axum', 'Next.js', 'PostGIS', 'Rust', 'TypeScript'],
    stars: 0,
    kind: 'application',
  },
  {
    name: 'wave-factory-essentials',
    description: 'Offline AU, VST3, and CLAP audio plug-ins for macOS and Windows, built with C++, DSP, and iPlug2.',
    language: 'C++',
    url: 'https://github.com/carlwelchdesign/wave-factory-essentials',
    homepage: null,
    updatedAt: '2026-08-11T19:52:38Z',
    topics: ['Audio Unit', 'VST3', 'CLAP', 'DSP', 'iPlug2'],
    stars: 0,
    kind: 'application',
  },
  {
    name: 'wave-factory-ai-production-assistant',
    description: 'A cross-DAW production assistant combining real-time audio analysis with guided mixing, sound design, and production workflows.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/wave-factory-ai-production-assistant',
    homepage: null,
    updatedAt: '2026-08-08T07:06:55Z',
    topics: ['Audio analysis', 'DAW', 'AI assistant'],
    stars: 0,
    kind: 'application',
  },
  {
    name: 'fruition-venture-studio',
    description: 'A venture-studio monorepo with a public founder-intake site and a separate owner-only idea-intelligence admin.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/fruition-venture-studio',
    homepage: 'https://fruition-venture-studio.vercel.app',
    updatedAt: '2026-07-31T20:31:43Z',
    topics: ['Next.js', 'Prisma', 'PostgreSQL', 'AI workflows'],
    stars: 0,
    kind: 'application',
  },
  {
    name: 'jobsearch-dashboard-ai',
    description: 'A local-first job-search system for role discovery, evidence management, truthful application materials, outcome tracking, and controlled workflows.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/jobsearch-dashboard-ai',
    homepage: null,
    updatedAt: '2026-07-17T11:07:48Z',
    topics: ['Next.js', 'LangGraph', 'MCP', 'PostgreSQL', 'Playwright'],
    stars: 3,
    kind: 'application',
  },
  {
    name: 'progression-lab-ai',
    description: 'An AI-assisted music-theory product for generating chord progressions, voicings, and arrangement ideas with playback, visualization, and sharing.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/progression-lab-ai',
    homepage: 'https://progressionlab.app',
    updatedAt: '2026-04-28T01:13:59Z',
    topics: ['Next.js', 'OpenAI', 'music theory', 'Tone.js', 'PostgreSQL'],
    stars: 2,
    kind: 'application',
  },
  {
    name: 'emf-disturbance-sim',
    description: 'An interactive 3D electromagnetic-field lab for simulating emitter behavior, interference patterns, and contested RF zones in real time.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/emf-disturbance-sim',
    homepage: 'https://emf-disturbance-sim.vercel.app/',
    updatedAt: '2026-04-17T18:16:13Z',
    topics: ['Next.js', 'React Three Fiber', '3D', 'simulation'],
    stars: 0,
    kind: 'application',
  },
  {
    name: 'webauthn-core',
    description: 'Reusable server-side WebAuthn orchestration with pluggable adapters for challenges, credentials, and MFA state.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/webauthn-core',
    homepage: null,
    updatedAt: '2026-04-01T18:43:58Z',
    topics: ['WebAuthn', 'MFA', 'authentication', 'adapters'],
    stars: 0,
    kind: 'library',
  },
  {
    name: 'netheria-ui',
    description: 'A TypeScript interface for configuring hardware targets, acceleration, and benchmark options with computed machine-readable output.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/netheria-ui',
    homepage: null,
    updatedAt: '2022-08-10T00:35:46Z',
    topics: ['hardware configuration', 'benchmarking', 'forms'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'spaceinvaders',
    description: 'A legacy JavaScript game project configured with a Gulp-based live development workflow.',
    language: 'JavaScript',
    url: 'https://github.com/carlwelchdesign/spaceinvaders',
    homepage: null,
    updatedAt: '2022-07-20T07:33:45Z',
    topics: ['JavaScript', 'Gulp', 'game'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'reviewtrackers-server',
    description: 'The Node and Docker server paired with the ReviewTrackers interface project.',
    language: 'JavaScript',
    url: 'https://github.com/carlwelchdesign/reviewtrackers-server',
    homepage: null,
    updatedAt: '2022-07-20T07:30:04Z',
    topics: ['Node.js', 'Docker', 'API'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'reviewtrackers-ui',
    description: 'A TypeScript web client paired with ReviewTrackers Server, including interactive tests and coverage scripts.',
    language: 'TypeScript',
    url: 'https://github.com/carlwelchdesign/reviewtrackers-ui',
    homepage: null,
    updatedAt: '2022-07-20T07:29:42Z',
    topics: ['TypeScript', 'web client', 'testing'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'react-native-message-loader',
    description: 'A React Native utility that polls an API for messages with configurable limits and update intervals.',
    language: 'JavaScript',
    url: 'https://github.com/carlwelchdesign/react-native-message-loader',
    homepage: null,
    updatedAt: '2017-11-21T00:55:21Z',
    topics: ['React Native', 'API polling'],
    stars: 0,
    kind: 'library',
  },
  {
    name: 'React.js-searchable-list',
    description: 'A legacy JavaScript searchable-list project with npm and Yarn development workflows.',
    language: 'JavaScript',
    url: 'https://github.com/carlwelchdesign/React.js-searchable-list',
    homepage: null,
    updatedAt: '2017-09-14T20:52:07Z',
    topics: ['React', 'search', 'list UI'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'cadillac',
    description: 'A legacy HTML repository. Its public metadata does not currently include a project description or README.',
    language: 'HTML',
    url: 'https://github.com/carlwelchdesign/cadillac',
    homepage: null,
    updatedAt: '2016-01-26T21:42:23Z',
    topics: ['HTML'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'TwitterFeedModule',
    description: 'A legacy JavaScript module for presenting a Twitter feed.',
    language: 'JavaScript',
    url: 'https://github.com/carlwelchdesign/TwitterFeedModule',
    homepage: null,
    updatedAt: '2015-09-26T01:57:51Z',
    topics: ['JavaScript', 'Twitter', 'feed'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'group_actions_CNI',
    description: 'A legacy JavaScript implementation of group actions for a client web application.',
    language: 'JavaScript',
    url: 'https://github.com/carlwelchdesign/group_actions_CNI',
    homepage: null,
    updatedAt: '2015-09-07T17:46:20Z',
    topics: ['JavaScript', 'web application'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'Primaloft',
    description: 'A legacy parallax website project built for Wildlife LA.',
    language: 'CSS',
    url: 'https://github.com/carlwelchdesign/Primaloft',
    homepage: null,
    updatedAt: '2014-10-30T20:31:41Z',
    topics: ['CSS', 'parallax', 'campaign site'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'Superman75thAniv',
    description: 'A legacy JavaScript repository. Its public metadata does not currently include a project description or README.',
    language: 'JavaScript',
    url: 'https://github.com/carlwelchdesign/Superman75thAniv',
    homepage: null,
    updatedAt: '2014-10-30T18:56:28Z',
    topics: ['JavaScript'],
    stars: 0,
    kind: 'legacy',
  },
  {
    name: 'TheConjuringSweepstakes',
    description: 'A PHP sweepstakes experience for The Conjuring, built for Trailer Park Studios.',
    language: 'PHP',
    url: 'https://github.com/carlwelchdesign/TheConjuringSweepstakes',
    homepage: null,
    updatedAt: '2014-10-30T18:52:27Z',
    topics: ['PHP', 'sweepstakes', 'campaign site'],
    stars: 0,
    kind: 'legacy',
  },
];
